Final - Thuan Nguyen - DetailUI - Personal Acount View
blkbrds/intern17_final_project_ThuanNguyen pull request #5
Opened 2022-06-17 01:40 UTC by mvn-thuannguyen-dn

2022-06-21 07:20 UTC, mvn-annguyen-dn requested changes
Please fix my comments and give a screenshot of UI Persional Account

2022-06-21 07:20 UTC, mvn-annguyen-dn commented on FinalProject/Views/Detail/Profile/ProfileViewController.swift
> +class ProfileViewController: UIViewController {
final

2022-06-21 07:20 UTC, mvn-annguyen-dn commented on FinalProject/Views/Detail/Profile/ProfileViewController.swift
> +    // MARK: - private funtions
line spacing. `function`

2022-06-21 07:20 UTC, mvn-annguyen-dn commented on FinalProject/Views/Detail/Profile/ProfileViewController.swift
> +    private func configTableView() {
line space

2022-06-21 07:20 UTC, mvn-annguyen-dn commented on FinalProject/Views/Detail/Profile/ProfileViewController.swift
> +    private func setupUI() {
line space

2022-06-21 07:20 UTC, mvn-annguyen-dn commented on FinalProject/Views/Detail/Profile/ProfileViewController.swift
> +    @objc private func settingsAction() {
line space

2022-06-21 07:20 UTC, mvn-annguyen-dn commented on FinalProject/Views/Detail/Profile/ProfileViewController.swift
> +extension ProfileViewController: UITableViewDelegate, UITableViewDataSource {
line space
separate `UITableViewDelegate` and `UITableViewDatasource`

2022-06-30 06:39 UTC, mvn-annguyen-dn reviewed
@mvn-thuannguyen-dn please upload screenshot UI

2022-07-05 02:57 UTC, mvn-thuannguyen-dn commented on FinalProject/Views/Base/BaseTabBarController.swift
> +        let homeViewController = LiveViewController()
Vì HomeViewController em chưa merge vào tabbar nên em chỉ để tạm thời khỏi lỗi

2022-07-05 04:58 UTC, mvn-annguyen-dn commented
Xin 500đ UI

2022-07-05 06:44 UTC, mvn-annguyen-dn reviewed
Check my comments

2022-07-06 01:53 UTC, mvn-thuannguyen-dn commented
1. UI_ProfileViewController
<img width="281" alt="Screenshot 2022-07-05 at 17 35 02" src="https://user-images.githubusercontent.com/102946498/177450235-2780c756-0933-44c9-917a-58c5378d886b.png">
2. UI_PlayerViewController
<img width="286" alt="Screenshot 2022-07-06 at 08 52 32" src="https://user-images.githubusercontent.com/102946498/177450606-ee0e4a5d-364c-46bf-8fac-e0d9cc572775.png">

2022-07-07 03:41 UTC, mvn-annguyen-dn approved these changes

2022-07-07 03:41 UTC, merged