Final - Thuan Nguyen - Api - HomeUI
blkbrds/intern17_final_project_ThuanNguyen pull request #7
Opened 2022-06-28 10:07 UTC by mvn-thuannguyen-dn

2022-06-30 07:01 UTC, mvn-annguyen-dn requested changes
@mvn-thuannguyen-dn thuan
please check my comments
add `final` and `private`
Thank you

2022-06-30 07:01 UTC, mvn-annguyen-dn commented on FinalProject/Views/Home/TableCells/HomeViewCell.swift
> +        return viewModel.items.count
viết gọn lại được không?

2022-07-05 03:49 UTC, mvn-thuannguyen-dn commented on FinalProject/Views/Home/HomeViewController.swift
> +                this.collectionView.reloadData()
dạ cần ạ

2022-07-05 04:46 UTC, mvn-thuannguyen-dn commented on FinalProject/Views/Home/HomeViewModel.swift
> +            return HomeCellViewModel(items: throwList, nameHeader: SectionType(rawValue: indexPath.row)?.nameSection)
Em chưa nghĩ ra được giải pháp nào tối ưu hơn, anh có giải pháp nào tốt hơn có thể hướng dẫn em với ạ

2022-07-05 04:50 UTC, mvn-thuannguyen-dn commented on FinalProject/Views/Home/HomeViewController.swift
> +            return Config.pickItems
lúc mới load vào thì api chưa trả về list các image nên lúc đầu em để bằng 0 sau đó khi có kết quả trả về rồi thì em mới lấy ra số lượng các item mong muốn

2022-07-05 04:52 UTC, mvn-thuannguyen-dn commented on FinalProject/Views/Home/TableCells/HomeViewCell.swift
> +        return viewModel.items.count
Em không nghĩ ra giải pháp tốt hơn, anh hướng dẫn giúp em với ạ

2022-07-05 05:00 UTC, mvn-thuannguyen-dn commented on FinalProject/Libraby/Ext/UIImageViewExt.swift
> +    }
em tạo function này để lấy dữ liệu  hình ảnh từ url

2022-07-05 07:03 UTC, mvn-annguyen-dn reviewed
Check my comments

2022-07-05 07:03 UTC, mvn-annguyen-dn commented on FinalProject/Views/Home/TableCells/HomeCellViewModel.swift
> +        let item = items[indexPath.row]
items[indexPath.row] nếu thằng này không tồn tại thì thế nào?

2022-07-05 07:03 UTC, mvn-annguyen-dn commented on FinalProject/Views/Home/TableCells/HomeViewCell.swift
> +        return viewModel.items.count
> return viewModel?.items.count ?? 0

2022-07-07 03:36 UTC, mvn-annguyen-dn submitted a review, later dismissed

2022-07-15 02:30 UTC, mvn-thuannguyen-dn commented
- [x] UI Detail Player Change 

<img width="283" alt="Screenshot 2022-07-15 at 08 42 24" src="https://user-images.githubusercontent.com/102946498/179134848-cc1b7f78-81b6-4319-ad76-9815c8214981.png">

2022-07-15 04:11 UTC, mvn-annguyen-dn approved these changes

2022-07-15 04:11 UTC, merged